export class Constants {
    static ZERO = 0;
    static EMPTY = '';
    static ONE = 1;
    static TEN = 10;
    static IDFOUR = 4;
    static CODE = '200';
    static OK = 'OK';
    static TYPE = 'http';
    static HUNDRED = 100;
    static ONESTRING = '1';
    static HUNDREDSTRING = '100';
    static IDHUNDRED = 10;
    static EMAIL1 = 'email1@gmail.com';
    static IDTWO = 2;
    static USER2 = 'user2';
    static EMAIL2 = 'email2@gmail.com';
    static PASSWORD2 = '123456';
    static USER10 = 'user10';
    static EMAIL10 = 'email10@gmail.com';
    static USER4 = 'usuario4';
    static EMAIL4 = 'email4@gmail.com';
    static IDFIVE = 5;
    static IDTEN = 10;
    static USER5 = 'usuario5';
    static EMAIL5 = 'email5@gmail.com';
    static PASSWORD5 = '123456';
    static IDSIX = 6;
    static USER6 = 'usuario6';
    static EMAIL6 = 'email6@gmail.com';
  }
  